# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SchoolAssistant' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SchoolAssistant
  pod 'SDWebImage'
  pod 'RealmSwift'
  pod 'Moya'
  pod 'Moya-ObjectMapper', '2.9'
  pod 'SnapKit'
  pod 'SPAlert'
  pod 'DeviceKit'

end
